version: '3'

services:
  web:
    command:
      gunicorn meteomap.site:app -b 0.0.0.0
      # python meteomap/site.py --debug
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      .env
    volumes:
        - ./meteomap:/meteomap/meteomap
        - ./downloads:/meteomap/downloads
        - ./logs:/meteomap/logs
        - ./config.json:/meteomap/config.json:ro
    ports:
      - "8000:8000"
      # - "5000:5000"
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "8084:5432"

volumes:
  meteomap:
