FROM python:3.5

WORKDIR /meteomap

ADD requirements.txt requirements.txt
ADD setup.py setup.py
# We need a directory to "-e"-install `meteomap`
RUN mkdir meteomap
RUN pip install -r requirements.txt

ADD config.json config.json
# Since we install the package with the -e option, we can actually add the code
# later. This way we don't need to rebuild everytime the code changes.
ADD meteomap meteomap

CMD ["gunicorn","meteomap.site:app", "-b", "0.0.0.0"]
