FROM python:3.5

WORKDIR /meteomap

ADD requirements.txt requirements.txt
ADD setup.py setup.py
ADD config.json config.json
ADD meteomap meteomap
RUN pip install -r requirements.txt
RUN rm -rf meteomap

CMD ["gunicorn","meteomap.site:app"]
# CMD ["python","meteomap/site.py"]
